import { Subject } from './types';

export const SUBJECTS: Subject[] = [
  {
    id: 'ds',
    name: 'Data Structures',
    color: '#3B82F6',
    difficulty: 3,
    enabled: false,
    topics: [
      { id: 'arrays', name: 'Arrays and Strings', enabled: true },
      { id: 'linked-lists', name: 'Linked Lists', enabled: true },
      { id: 'stacks', name: 'Stacks', enabled: true },
      { id: 'queues', name: 'Queues', enabled: true },
      { id: 'trees', name: 'Trees', enabled: true },
      { id: 'graphs', name: 'Graphs', enabled: true },
      { id: 'hash-tables', name: 'Hash Tables', enabled: true },
      { id: 'heaps', name: 'Heaps', enabled: true },
    ],
  },
  {
    id: 'algo',
    name: 'Algorithms',
    color: '#EF4444',
    difficulty: 4,
    enabled: false,
    topics: [
      { id: 'sorting', name: 'Sorting Algorithms', enabled: true },
      { id: 'searching', name: 'Searching Algorithms', enabled: true },
      { id: 'dynamic', name: 'Dynamic Programming', enabled: true },
      { id: 'greedy', name: 'Greedy Algorithms', enabled: true },
      { id: 'divide-conquer', name: 'Divide and Conquer', enabled: true },
      { id: 'backtracking', name: 'Backtracking', enabled: true },
      { id: 'graph-algos', name: 'Graph Algorithms', enabled: true },
    ],
  },
  {
    id: 'os',
    name: 'Operating Systems',
    color: '#10B981',
    difficulty: 3,
    enabled: false,
    topics: [
      { id: 'processes', name: 'Processes and Threads', enabled: true },
      { id: 'memory', name: 'Memory Management', enabled: true },
      { id: 'cpu-scheduling', name: 'CPU Scheduling', enabled: true },
      { id: 'deadlocks', name: 'Deadlocks', enabled: true },
      { id: 'file-systems', name: 'File Systems', enabled: true },
      { id: 'io', name: 'I/O Management', enabled: true },
    ],
  },
  {
    id: 'dbms',
    name: 'Database Management Systems',
    color: '#F59E0B',
    difficulty: 3,
    enabled: false,
    topics: [
      { id: 'relational-model', name: 'Relational Model', enabled: true },
      { id: 'sql', name: 'SQL', enabled: true },
      { id: 'normalization', name: 'Normalization', enabled: true },
      { id: 'transactions', name: 'Transactions', enabled: true },
      { id: 'concurrency', name: 'Concurrency Control', enabled: true },
      { id: 'recovery', name: 'Recovery', enabled: true },
    ],
  },
  {
    id: 'cn',
    name: 'Computer Networks',
    color: '#8B5CF6',
    difficulty: 3,
    enabled: false,
    topics: [
      { id: 'osi-model', name: 'OSI Model', enabled: true },
      { id: 'tcp-ip', name: 'TCP/IP', enabled: true },
      { id: 'routing', name: 'Routing', enabled: true },
      { id: 'transport', name: 'Transport Layer', enabled: true },
      { id: 'application', name: 'Application Layer', enabled: true },
      { id: 'network-security', name: 'Network Security', enabled: true },
    ],
  },
  {
    id: 'se',
    name: 'Software Engineering',
    color: '#EC4899',
    difficulty: 2,
    enabled: false,
    topics: [
      { id: 'sdlc', name: 'SDLC Models', enabled: true },
      { id: 'requirements', name: 'Requirements Engineering', enabled: true },
      { id: 'design', name: 'Software Design', enabled: true },
      { id: 'testing', name: 'Software Testing', enabled: true },
      { id: 'maintenance', name: 'Software Maintenance', enabled: true },
      { id: 'agile', name: 'Agile Methodologies', enabled: true },
    ],
  },
  {
    id: 'toc',
    name: 'Theory of Computation',
    color: '#06B6D4',
    difficulty: 4,
    enabled: false,
    topics: [
      { id: 'automata', name: 'Automata Theory', enabled: true },
      { id: 'languages', name: 'Formal Languages', enabled: true },
      { id: 'grammars', name: 'Grammars', enabled: true },
      { id: 'turing', name: 'Turing Machines', enabled: true },
      { id: 'complexity', name: 'Complexity Theory', enabled: true },
    ],
  },
  {
    id: 'cd',
    name: 'Compiler Design',
    color: '#84CC16',
    difficulty: 4,
    enabled: false,
    topics: [
      { id: 'lexical', name: 'Lexical Analysis', enabled: true },
      { id: 'syntax', name: 'Syntax Analysis', enabled: true },
      { id: 'semantic', name: 'Semantic Analysis', enabled: true },
      { id: 'code-gen', name: 'Code Generation', enabled: true },
      { id: 'optimization', name: 'Code Optimization', enabled: true },
    ],
  },
  {
    id: 'coa',
    name: 'Computer Organization & Architecture',
    color: '#F97316',
    difficulty: 3,
    enabled: false,
    topics: [
      { id: 'digital-logic', name: 'Digital Logic', enabled: true },
      { id: 'cpu-design', name: 'CPU Design', enabled: true },
      { id: 'memory-org', name: 'Memory Organization', enabled: true },
      { id: 'io-org', name: 'I/O Organization', enabled: true },
      { id: 'pipelining', name: 'Pipelining', enabled: true },
    ],
  },
  {
    id: 'maths',
    name: 'Engineering Mathematics',
    color: '#6366F1',
    difficulty: 3,
    enabled: false,
    topics: [
      { id: 'discrete-math', name: 'Discrete Mathematics', enabled: true },
      { id: 'linear-algebra', name: 'Linear Algebra', enabled: true },
      { id: 'calculus', name: 'Calculus', enabled: true },
      { id: 'probability', name: 'Probability', enabled: true },
      { id: 'statistics', name: 'Statistics', enabled: true },
    ],
  },
  {
    id: 'web',
    name: 'Web Technologies',
    color: '#14B8A6',
    difficulty: 2,
    enabled: false,
    topics: [
      { id: 'html-css', name: 'HTML & CSS', enabled: true },
      { id: 'javascript', name: 'JavaScript', enabled: true },
      { id: 'react', name: 'React', enabled: true },
      { id: 'node', name: 'Node.js', enabled: true },
      { id: 'databases', name: 'Web Databases', enabled: true },
      { id: 'apis', name: 'REST APIs', enabled: true },
    ],
  },
  {
    id: 'ai',
    name: 'Artificial Intelligence',
    color: '#DC2626',
    difficulty: 4,
    enabled: false,
    topics: [
      { id: 'search', name: 'Search Algorithms', enabled: true },
      { id: 'ml', name: 'Machine Learning', enabled: true },
      { id: 'nlp', name: 'Natural Language Processing', enabled: true },
      { id: 'vision', name: 'Computer Vision', enabled: true },
      { id: 'expert-systems', name: 'Expert Systems', enabled: true },
      { id: 'neural-networks', name: 'Neural Networks', enabled: true },
    ],
  },
];